### ISSUE TITLE
uninstalling homer

### ISSUE THREAD

**Issue by alok** [tubbo/homer#1]
I uninstalled homer with `brew uninstall homer` and it ended up wiping out my previous config, including my old ~/.zshrc. Is there any way to restore those files or revert via homer?

**Comment by tubbo** [comment]
Homer should have created a Git repo in your home directory and added all of your configuration files to it, so that you can revert your changes in case anything goes wrong. What does `git status` from your home directory say?

**Comment by alok** [comment]
"Nothing added to commit but untracked files present"

It then lists my entire home directory as untracked.

**Comment by tubbo** [comment]
@Alok sorry I totally missed this...my fault. anyway, the way homer works is by making your home directory a git repo but it doesn't add any files automatically, because a lot of people keep unsafe credentials in these dot files that they don't necessarily want published. You can use `homer add FILENAME -m "commit message"` or just `git add -f FILENAME && git commit -am "commit message"` to add the files you want in there. Re-reading the README it seems like that part of the story wasn't really emphasized enough, so I'll definitely make it more clear in the documentation. Sorry if this screwed up any of your configs...I made this for my own usage and never had a chance to really give it a good test "in the wild", but it works for me.

It should also be noted that while Homer is written in ZSH shell script and thus depends on `zsh` in order to run, it doesn't have to be your default shell and Homer can be used with anything as long as ZSH is installed.

Homer doesn't actually store or keep track of your files, it's really just a shell script interface to the Git repo that's created in your home directory with the convention of ignoring everything until explicitly added, giving you full control over your dotfiles repo.
